### ISSUE TITLE
HTTP response code 403 received, expected HTTP 201

### ISSUE THREAD

**Issue by felipecao** [eonx-com/actions-opsgenie#4]
Hello, everyone! 

First of all, thanks a lot for the effort in putting together this Gitthub Action for the community, really appreciate it :) 

I'm having some trouble using the action though, I was wondering if anyone could give me a hand figuring out what i'm doing wrong.

This is how the action is declared in my workflow: 

```
      - name: Notify Opsgenie
        if: failure()
        uses: eonx-com/actions-opsgenie@master
        with:
          API_KEY: ${{ secrets.OPSGENIE_GITHUB_ACTIONS_API_KEY }}
          PRIORITY: 'P1'
          ALIAS: 'end-2-end-tests-prod'
          MESSAGE: 'E2E tests failed when running against prod'
          USE_EU_INSTANCE: true
```

And when the action kicks in, i'm getting the error message mentioned in the title: `ERROR: HTTP response code 403 received, expected HTTP 201`

Any idea what I could be doing wrong here? Could it be somehow related to `USE_EU_INSTANCE`? (the API key I've created has all the possible permissions, btw)

Thanks a lot!
